sudo: required
dist: trusty

language: python
python:
  - '3.5'

before_install:
  - cd ..
  - git clone https://github.com/robinsax/canvas.git
  - cd canvas
  - sudo ./etc/install_dependencies.sh
  - npm conf set strict-ssl false
  - python3 canvas --init --config plugins.directory=.. "plugins.activated=xml,"
  - python3 canvas --write-setup-sql | sudo -u postgres psql
  - cd ../cvpl-xml
  - export PYTHONPATH="../canvas"

script:
  - coverage run -m canvas --test xml

after_success:
  - coveralls
