sudo: required
dist: trusty

language: python
python:
  - '3.5'

before_install:
  - cd ..
  - git clone https://github.com/robinsax/canvas.git
  - cd canvas
  - sudo ./etc/install_dependencies.sh
  - npm conf set strict-ssl false
  - python3 canvas --init 
  - python3 canvas --config "plugins.directory=.." "plugins.activated=filestore,"
  - python3 canvas --write-setup-sql | sudo -u postgres psql
  - cd ../cvpl-filestore
  - export PYTHONPATH="../canvas"

script:
  - coverage run -m canvas --test filestore

after_success:
  - coveralls
